### ISSUE TITLE
Incorrectly formatted commit message causes dvol log to fail

### ISSUE THREAD

**Issue by brendan-donegan** [ClusterHQ/dvol#18]
Making a commit with a badly formatted message causes dvol log to traceback as shown below. Admittedly the commit message here is somewhat deliberately misformatted - I would need to do a bit more investigation to see exactly what formatting causes this.

```
brendand@brendand-T450:~/dvol-test$ dvol commit --message="clean stateDF"R$£":R£$F:$£F£:"
59c9f06ad0a54613a72a42d15e29d32e1ef9ac3e
brendand@brendand-T450:~/dvol-test$ dvol log
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/bin/dvol", line 9, in <module>
    load_entry_point('dvol==0.1', 'console_scripts', 'dvol')()
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 629, in main
    
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/task.py", line 882, in react
    finished = main(_reactor, *argv)
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 605, in _main
    
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 598, in postOptions
    
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 425, in run
    
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 330, in listCommits
    
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 101, in output
    
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 118: ordinal not in range(128)

brendand@brendand-T450:~/dvol-test$ dvol ls
  VOLUME   BRANCH   CONTAINERS        
* moby     master   /dvoltest_redis_1 
brendand@brendand-T450:~/dvol-test$ dvol log
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/bin/dvol", line 9, in <module>
    load_entry_point('dvol==0.1', 'console_scripts', 'dvol')()
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 629, in main
    
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/task.py", line 882, in react
    finished = main(_reactor, *argv)
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 605, in _main
    
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/usage.py", line 277, in parseOptions
    self.postOptions()
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 598, in postOptions
    
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 425, in run
    
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 330, in listCommits
    
  File "build/bdist.linux-x86_64/egg/dvol/dvol.py", line 101, in output
    
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 118: ordinal not in range(128)

```

**Comment by brendan-donegan** [comment]
Update: I can reproduce this now with as simple a message as:

dvol commit -m "Clean state worth £30"
